services:
  stadtbahn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4011:4011"
    env_file:
      - .env
    restart: unless-stopped

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "4012:4012"
    restart: unless-stopped