server {
    listen 4011;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.htm(l)?$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}